-- TMDB_movie_dataset_v11.csv -> movies

CREATE TABLE movies (
    id                   INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- TMDB id from the CSV, or auto-assigned when omitted
    title                TEXT        NOT NULL,
    vote_average         NUMERIC(5, 3),
    vote_count           INTEGER,
    status               TEXT,                          -- Released, Post Production, ...
    release_date         DATE,
    revenue              BIGINT,
    runtime              INTEGER,
    adult                BOOLEAN     NOT NULL DEFAULT FALSE,
    backdrop_path        TEXT,
    budget               BIGINT,
    homepage             TEXT,
    imdb_id              TEXT,
    original_language    TEXT,                          -- ISO 639-1
    original_title       TEXT,
    overview             TEXT,
    popularity           NUMERIC(10, 3),
    poster_path          TEXT,
    tagline              TEXT,
    genres               TEXT[]      NOT NULL DEFAULT '{}',
    production_companies TEXT[]      NOT NULL DEFAULT '{}',
    production_countries TEXT[]      NOT NULL DEFAULT '{}',
    spoken_languages     TEXT[]      NOT NULL DEFAULT '{}',
    keywords             TEXT[]      NOT NULL DEFAULT '{}'
);

CREATE INDEX movies_imdb_id_idx          ON movies (imdb_id);
CREATE INDEX movies_release_date_idx     ON movies (release_date);
CREATE INDEX movies_popularity_idx       ON movies (popularity DESC);
CREATE INDEX movies_original_language_idx ON movies (original_language);

-- Array membership lookups: WHERE genres @> ARRAY['Action']
CREATE INDEX movies_genres_idx   ON movies USING GIN (genres);
CREATE INDEX movies_keywords_idx ON movies USING GIN (keywords);


-- Optional: full-text search column, weighted title > tagline/keywords > overview
ALTER TABLE movies ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(tagline, '')), 'B') ||
        setweight(to_tsvector('english', array_to_string(keywords, ' ')), 'B') ||
        setweight(to_tsvector('english', coalesce(overview, '')), 'C')
    ) STORED;

CREATE INDEX movies_search_vector_idx ON movies USING GIN (search_vector);

-- Optional: fuzzy / prefix title matching
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX movies_title_trgm_idx ON movies USING GIN (title gin_trgm_ops);
